---
- hosts: all
  become: yes
  tasks:
      - name: install Apache2
        apt:
           name: Apache2
           state: present
      - name: Apache service
        service: 
            name: Apache2
            state: started

